DietPlanner/DietPlanner/Controllers/RoleBasedRedirectionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class RoleBasedRedirectionController : Controller
    {

        public async Task<IActionResult> DashboardRedirection()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = HttpContext.User.Claims;
                string roles = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                if (roles.Contains("Admin"))
                {
                    return RedirectToAction("Index", "Home");
               
                }
                else if (roles.Contains("User"))
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            return View();
        }

        public async Task<IActionResult> MealPlannerRedirection()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = HttpContext.User.Claims;
                string roles = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                if (roles.Contains("Admin"))
                {
                    return RedirectToAction("ViewMealPlan", "AdminMealPlanner");
                }
                else if (roles.Contains("User"))
                {
                    return RedirectToAction("PlanDashboard", "UserMealPlanner");
                }
                
            }
            return View();
        }

        public async Task<IActionResult> ChallengesRedirection()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = HttpContext.User.Claims;
                string roles = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                if (roles.Contains("Admin"))
                {
                    return RedirectToAction("ViewChallenges", "AdminChallenges");
                }
                else if (roles.Contains("User"))
                {
                    return RedirectToAction("ChallengeDashboard", "UserChallenges");
                }

            }
            return View();
        }

        public async Task<IActionResult> ActivityRedirection()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = HttpContext.User.Claims;
                string roles = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                if (roles.Contains("Admin"))
                {
                    return RedirectToAction("UserActivity", "UserActivityTracking");
                }
                else if (roles.Contains("User"))
                {
                    return RedirectToAction("UserActivity", "UserActivityTracking");
                }

            }
            return View();
        }
        public async Task<IActionResult> FeedRedirection()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = HttpContext.User.Claims;
                string roles = claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                if (roles.Contains("Admin"))
                {
                    return RedirectToAction("PublicFeed", "Feed");
                }
                else if (roles.Contains("User"))
                {
                    return RedirectToAction("PublicFeed", "Feed");
                }

            }
            return View();
        }
    }
   
}

DietPlanner/DietPlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Layout.css" />
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>

<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle">
            <i class="bx bx-menu" id="header-toggle"></i>
        </div>

        <div>
            <div class="profile">
                <div class="user">
                    <h4>Hey, <span id="username"></span></h4>
                </div>
               
                <div class="header_img img-box">
                    <img id="userImage" alt="User Image" />
                </div>
            
            </div>
            <div class="menu">
                <ul>
                    <li>
                        <a asp-controller="ProfileDetail" asp-action="ViewProfile"><i class="bx bx-user"></i>&nbsp;Profile</a>
                    </li>
                   @*  <li>
                        <a href="#"><i class="bx bx-help-circle"></i>&nbsp;Help</a>
                    </li> *@
                    <li>
                        <a asp-controller="Auth" asp-action="Logout"><i class="bx bx-log-out ph-sign-out"></i>&nbsp;Sign Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="#" class="nav_logo">
                    <i class="bx bxs-food-menu nav_logo-icon"></i>
                    <span class="nav_logo-name">DietPlanner</span>
                </a>

                <div class="nav_list">
                    <a asp-controller="RoleBasedRedirection" asp-action="DashboardRedirection" class="nav_link">
                        <i class="bx bx-grid-alt nav_icon"></i>
                        <span class="nav_name">Dashboard</span>
                    </a>
                    
                    <a asp-controller="RoleBasedRedirection" asp-action="MealPlannerRedirection" class="nav_link">
                        <i class="bx bxs-bowl-rice nav_icon"></i>
                        <span class="nav_name">Food Planning</span>
                    </a>
                    <a asp-controller="RoleBasedRedirection" asp-action="ChallengesRedirection" class="nav_link">
                        <i class="bx bxs-trophy nav_icon"></i>
                        <span class="nav_name">Challenges</span>
                    </a>
                    <a asp-controller="RoleBasedRedirection" asp-action="ActivityRedirection" class="nav_link">
                        <i class='bx bx-cycling'></i>                        
                        <span class="nav_name">Activity Tracking</span>
                    </a>
                    <a asp-controller="RoleBasedRedirection" asp-action="FeedRedirection" class="nav_link">
                        <i class="bx bx-message-square-detail nav_icon"></i>
                        <span class="nav_name">Feeds</span>
                    </a> 
                </div>
            </div>
            
        </nav>
    </div>

    <div class="mt-3">

        <main role="main" class="pt-5 pb-3">
            @RenderBody()
        </main>

    </div>

    <script src="~/js/Layout.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)

    </body>

</html>